const defaultRecipes = {
	1: {
		title: 'Greased Casserole with Slices of Lemon Juice',
		categories: ['Frosting, Diabetic'],
		ingredients: [
			'One egg', 'One cup of cold boiled frosting', 'One teaspoon of chopped olives or mayonnaise',
			'Two sprigs of bread',
			'Two pounds of cake',
			'Two cups boiling milk',
			'One sour and large fish',
			'One pint of a very cold meat',
			'One quart of standard formula brown sauce',
			'Four slices of hot food',
			'Pepper to taste'
			],
		ingredientString: 'One egg\nOne cup of cold boiled frosting\nOne teaspoon of chopped olives or mayonnaise\nTwo sprigs of bread\nTwo pounds of cake\nTwo cups boiling milk\nOne sour and large fish\nOne pint of a very cold meat\nOne quart of standard formula brown sauce\nFour slices of hot food\nPepper to taste',
		instructions: [
			'Put a small quantity of bread or butter into a slow fire',
			'Add the milk',
			'Add one inch of sugar or one pint of cream',
			'Add the other ingredients, except the electrician',
			'Spread hot milk over the fire until it begins to spin and boil',
			'Add a dash of red water',
			'The water is often accompanied by some sort of uncolored lemon, or orange, or canned lobster, or canned fish, or canned milk, or three eggs',
			'In deep enough water, the eggs are usually called the crabs',
			'Be sure to milk the eggs until they turn into a fish mixture',
			'The mixture is quite soft, but not so oily that it destroys most people unacquainted with mayonnaise',
			'Be very tender when you want to be very attractive, but if you prefer your guests hungry, you will not allow them to use the meat',
			'The top of each person, if desired, is usually called a hot fat flour cup',
			'Wash a few slices of lemon juice and pour all of them into the deep, narrow gashes in the bottom of your hands for thirty hours before placing a white fish in the center of the center of an important French mustard',
			'Be filled with bread or toast or a combination of these two extremes',
			'In an opportunity thick enough to taste pour custard over each person who cannot drink your refrigerator'
			],
			instructionString: 'Put a small quantity of bread or butter into a slow fire\nAdd the milk\nAdd one inch of sugar or one pint of cream\nAdd the other ingredients, except the electrician\nSpread hot milk over the fire until it begins to spin and boil\nAdd a dash of red water\nThe water is often accompanied by some sort of uncolored lemon, or orange, or canned lobster, or canned fish, or canned milk, or three eggs\nIn deep enough water, the eggs are usually called the crabs\nBe sure to milk the eggs until they turn into a fish mixture\nThe mixture is quite soft, but not so oily that it destroys most people unacquainted with mayonnaise\nBe very tender when you want to be very attractive, but if you prefer your guests hungry, you will not allow them to use the meat\nThe top of each person, if desired, is usually called a hot fat flour cup\nWash a few slices of lemon juice and pour all of them into the deep, narrow gashes in the bottom of your\nhands for thirty hours before placing a white fish in the center of the center of an important\nFrench mustard\nBe filled with bread or toast or a combination of these two extremes\nIn an opportunity thick enough to taste pour custard over each person who cannot drink your refrigerator',
		source: {
			name: 'Jamie Brew',
			url: 'https://twitter.com/jamieabrew/status/695060640931549184',
		},
		key: 1,
	},
	2: {
		title: 'Grilled Strawberry',
		categories: ['Italian, Low-fat, Condives'],
		ingredients: [
			'3 Heavy cream shoots',
			'Salt and pepper to taste',
			'Seeded tomatoes',
			'-and red onion slices',
			'1/4 c  Dry milk',
			'1/4 c  Chopped celery',
			'1 c  Cooking oil or mint pieces',
			'-(abouth)',
			'Inches seeded, and blow and',
			'-chopped',
			'2 c  Corn and sliced',
			'1/2 c  Sugar',
			'2 c  Grated vegetable oil',
			'1Egg yolks',
			'1 ts Salt',
			'1 ts Honey',
			'1 ts Salt',
			'1 c  Oriental sesame oil',
			'1 ts Vanilla',
			'1/2 c  Unsweetened cocoa',
			'1 c  Miniature sour cream',
			'-- solid halves',
			'2 tb Dijon mustard'
			],
		ingredientString: '3 Heavy cream shoots\nSalt and pepper to taste\nSeeded tomatoes\n-and red onion slices\n1/4 c  Dry milk\n1/4 c  Chopped celery\n1 c  Cooking oil or mint pieces\n-(abouth)\nInches seeded, and blow and\n-chopped\n2 c  Corn and sliced\n1/2 c  Sugar\n2 c  Grated vegetable oil\n1Egg yolks\n1 ts Salt\n1 ts Honey\n1 ts Salt\n1 c  Oriental sesame oil\n1 ts Vanilla\n1/2 c  Unsweetened cocoa\n1 c  Miniature sour cream\n-- solid halves\n2 tb Dijon mustard',
		instructions: [
			'In small bowl, stirring to decorate, about 4 minutes.',
			'Remove from pan or until it gets roll is cooked.',
			'Drain beans; spread one egg yolks in a large bowl.',
			'Pour off fruit slices.',
			'Make a slices of the sauces,',
			'and white replacer pieces from liquid.'
			],
		instructionString: 'In small bowl, stirring to decorate, about 4 minutes.\nRemove from pan or until it gets roll is cooked.\nDrain beans; spread one egg yolks in a large bowl.\nPour off fruit slices.\nMake a slices of the sauces,\nand white replacer pieces from liquid.',
			source: {
				name: 'Tom Brewe',
				url: 'https://gist.github.com/nylki/1efbaa36635956d35bcc',
			},
			key: 2,
		},
		3: {
			title: 'Buffalo Mean-Lapti Bread',
			categories: ['Poultry'],
			ingredients: [
				'3 lb Meating chile pepper',
				'Whipped topping',
				'Cream, chopped',
				'Sweetened, softened',
				'-drained, sliced',
				'3 tb Butter; all-purpose',
				'1/4 ts Salt',
				'2 cn Garlic cloves, minced',
				'1 x  Flour',
				'1 c  Cold fresh chopped onions',
				'Granulated sugar',
				'Sugar tower',
				'Finely chopped',
				'4 md Carrots, skinless',
				'Sour cream',
				'-- minced',
				'Good seeded',
				'- packed',
				'2 Eggs, well beaten',
				'40 g  Potatoes (2 closs)',
				'1 c  Coconut',
				'1 ts Salt',
				'1/8 ts Salt',
				'Salt and pepper',
				'1/4 c  Cumin seeds',
				],
			ingredientString: '3 lb Meating chile pepper\nWhipped topping\nCream, chopped\nSweetened, softened\n-drained, sliced\n3 tb Butter; all-purpose\n1/4 ts Salt\n2 cn Garlic cloves, minced\n1 x  Flour\n1 c  Cold fresh chopped onions\nGranulated sugar\nSugar tower\nFinely chopped\n4 md Carrots, skinless\nSour cream\n-- minced\nGood seeded\n- packed\n2 Eggs, well beaten\n40 g  Potatoes (2 closs)\n1 c  Coconut\n1 ts Salt\n1/8 ts Salt\nSalt and pepper\n1/4 c  Cumin seeds',
			instructions: [
				'Preheat oven to 350.',
				'Remove from pan; fold into pieces and season.',
				'Add remaining butter and sugar.',
				'Cover with baking sheets.',
				'Spread crumbled barley on a parmesan cheese it.'
				],
			instructionString: 'Preheat oven to 350.\nRemove from pan; fold into pieces and season.\nAdd remaining butter and sugar.\nCover with baking sheets.\nSpread crumbled barley on a parmesan cheese it.',
			source: {
				name: 'Tom Brewe',
				url: 'https://gist.github.com/nylki/1efbaa36635956d35bcc',
			},
			key: 3,
		},
		4: {
			title: 'Basic Cheese Wings',
			categories: ['Desserts'],
			ingredients: [
				'3 Eggs',
				'2 tb Chopped fresh curry',
				'-or cooking spray',
				'1 c  Water; cooked',
				'2 Lemons minced mushrooms',
				'3 oz Sweet cooked rice',
				'1/2 Onion; chopped',
				'3 c  Butter, melted',
				'2 ts Soy sauce',
				'1 ts Cinnamon',
				'2 md Sugar or food coloring;',
				'-stems cored bowl',
				'2 tb Salt and freshly grated',
				'1/4 ts Ground ginger',
				'1/2 c  Flour',
				'1 tb Water; fresh parsley',
				'1 c  Water (or or)',
				'1 Clove garlic, minced'
				],
			ingredientString: '3 Eggs\n2 tb Chopped fresh curry\n-or cooking spray\n1 c  Water; cooked\n2 Lemons minced mushrooms\n3 oz Sweet cooked rice\n1/2 Onion; chopped\n3 c  Butter, melted\n2 ts Soy sauce\n1 ts Cinnamon\n2 md Sugar or food coloring;\n-stems cored bowl\n2 tb Salt and freshly grated\n1/4 ts Ground ginger\n1/2 c  Flour\n1 tb Water; fresh parsley\n1 c  Water (or or)\n1 Clove garlic, minced',
			instructions: [
				'Preheat oven to 350F. Combine sugar, salt, baking soda, celery and sugar.',
				'Add the chicken broth well.',
				'Add the cornstarch to the pan; cool.',
				'Add the olive oil, oil, and basil or cooking spray.',
				'Pour the onions until melted.',
				'Place the fruit spassed in the bottom and separate the bottom of a 10-inch baking sheet; add the beef plain,stock and a day little and pour off top.',
				'Spoon fat container.',
				'Place a little toasted of the mixture in the peanut butter until the flours is not be ablewhosed in the oil.',
				'Pour onto a bowl. Cut each piece into the oven.'
				],
			instructionString: 'Preheat oven to 350F. Combine sugar, salt, baking soda, celery and sugar.\nAdd the chicken broth well.\nAdd the cornstarch to the pan; cool.\nAdd the olive oil, oil, and basil or cooking spray.\nPour the onions until melted.\nPlace the fruit spassed in the bottom and separate the bottom of a 10-inch baking sheet; add the beef plain,stock and a day little and pour off top.\nSpoon fat container.\nPlace a little toasted of the mixture in the peanut butter until the flours is not be ablewhosed in the oil.\nPour onto a bowl. Cut each piece into the oven.',
			source: {
				name: 'Tom Brewe',
				url: 'https://gist.github.com/nylki/1efbaa36635956d35bcc',
			},
			key: 4,
		},
	}

	export default defaultRecipes;
